### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by brycecammo** [tiff/wysihtml5#84] opened 2012-05-24 04:25 UTC
It would be nice to be able to create nested ul/ol elements. Pressing tab while in a ul/ol would add another 'level'. For example:
- level 1
  - level 2
- level 1 again

P.S. Great job with wysihtml5 - it was just what I was looking for :)

**Comment by tiff** [comment] 2012-05-24 08:15
This is definitely planned to be part of wysihtml5. There's already a pull request by @qrush waiting for review: https://github.com/xing/wysihtml5/pull/53

**Comment by brycecammo** [comment] 2012-05-24 12:35
So apparently I need to learn how to use the search feature :)

**Comment by tiff** [comment] 2012-05-25 00:27
Duplicate of #53

**Closed as completed by tiff** 2012-05-25 00:27 UTC
