### ISSUE TITLE
The 'numbers' method in check_attributes should do value suffix, too?

### ISSUE THREAD

**Issue by JonFabritius** [tiff/wysihtml5#215] opened 2012-09-18 20:29 UTC
**Could the 'numbers' method for checking attributes be extended to something like 'dimensions', allowing for the value suffix, at the least the percentage sign '%'.**

Numbers come in many flavors.

Case in point: When attempting to paste an iframe embed from Soundcloud, for example, the original iframe snippet contains width and height values for "100%" and "162px" as the content height varies. This is good to have, since  resizing iframes based on content is annoyingly complex.

To allow the attributes, AFAIK one must whitelist them, and the only method appears to be the "check_attributes" option. However,

```
"iframe": {
  "check_attributes": {
    "width": "numbers",
    "height": "numbers"
    }
}
```

results in the unit suffixes being stripped, resulting in arbitrary proportions.

(Or is there another method for whitelisting attributes?)

**Comment by tiff** [comment] 2012-09-27 23:04
I'm planning to drastically change how the parser rules work. With v0.4 you'll be able to define a regular expression or a  function. Thanks for your heads up.

**Comment by tiff** [comment] 2012-09-27 23:50
btw. duplicate of #130

**Closed as completed by tiff** 2012-09-27 23:50 UTC
