### ISSUE TITLE
Multiple editors on a single toolbar

### ISSUE THREAD

**Issue by ehubin** [tiff/wysihtml5#220] opened 2012-09-22 16:20 UTC
Would it be complicated to allow for a single toolbar to control several editors on the same page.

I would need this feature as i have multiple small editors on a page and having one toolbar for each would be overkill.

**Comment by ehubin** [comment] 2012-09-22 16:26
Looking closer it seems there is a pull request pending for this. Any chance to get it included?

**Comment by tiff** [comment] 2012-09-27 22:50
The problem with that pull request https://github.com/xing/wysihtml5/pull/145 is that the diff is unreadable. I might be more motivated to look into this if it's a clean and proper diff.

**Comment by tiff** [comment] 2012-09-27 22:50
I'm closing this as a duplicate of #145

**Closed as completed by tiff** 2012-09-27 22:50 UTC
