### ISSUE TITLE
Undo doesn't work after a paste

### ISSUE THREAD

**Issue by javan** [tiff/wysihtml5#10] opened 2011-12-12 22:25 UTC
After pasting, cmd-z doesn't undo anything (in Chrome, Safari, and FF). Not sure if this is a bug or a reality of contentEditable.

Undo works fine after typing.

**Comment by tiff** [comment] 2011-12-18 23:49
The issue is not only happening after pasting but also after some other actions.

I'm working on this one already. Check the "undo_manager" branch.
wysihtml5 makes heavy use of the selection api. Unless native query commands the selection api doesn't create entries in the browser's undo history. Therefore wysihtml5 needs to fake the undo/redo management.

**Comment by tiff** [comment] 2012-02-05 19:41
I merged the undo_manager branch into master. That means that we now have a "fake" undo/redo history for all browsers (except IE).

**Closed as completed by tiff** 2012-02-05 19:41 UTC

**Comment by tiff** [comment] 2012-02-05 19:43
Commit message (for the sake of completeness) ea4e28a85cfbe831e82b8b1ce39a727350c5b80e
